// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwwgxcmmccnkbvxsacm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d3dneGNtbWNjbmtidnhzYWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODYzNzIsImV4cCI6MjA2OTk2MjM3Mn0.jWIKReOlg91wSQein6clw96fvxiTYCry6LfnilKiChM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});